import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    padding: 10,
  },
  list: {
    borderColor: "#00bfff",
    borderWidth: 0,
    borderRadius: 5,
    alignSelf: "stretch",
    width: 300,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#00bfff",
    borderColor: "#00bfff",
    borderRadius: 5,
    padding: 5,
    height: 40,
    margin: 5,
  },

  input: {
    borderColor: "#00bfff",
    height: 40,
    margin: 12,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    alignSelf: "stretch",
  },
  searchInput: {
    borderColor: "#00bfff",
    height: 40,
    margin: 20,
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    alignSelf: "stretch",
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    backgroundColor: "#fff8dc",
    width: 300,
  },
  title2: {
    fontSize: 20,
    fontWeight: "bold",
    //backgroundColor: "#fff8dc",
    alignSelf: "stretch",
    marginBottom: 5,
    marginLeft: 5,
  },
  title3: {
    fontSize: 16,
    fontWeight: "bold",
  },
  content: {
    fontSize: 16,
    padding: 5,
    fontWeight: "bold",
    backgroundColor: "#f0ffff",
    borderColor: "#00bfff",

    borderWidth: 1,
    borderRadius: 5,
    margin: 2,
    alignSelf: "stretch",
    width: 350,
  },
  content2: {
    fontSize: 16,
    padding: 5,
    fontWeight: "bold",
    backgroundColor: "#f0ffff",
    borderColor: "#00bfff",
    borderWidth: 1,
    borderRadius: 5,
    margin: 2,
    alignSelf: "stretch",
    width: 330,
  },
  imagePreview: {
    height: 100,
    width: 100,
    borderColor: "#00bfff",
    borderWidth: 2,
    borderRadius: 5,
    marginBottom: 2,
  },
  quantity: {
    borderColor: "#00bfff",
    backgroundColor: "#f0ffff",
    borderWidth: 1,
    borderRadius: 5,
  },
  cardField: {
    fontSize: 16,
    padding: 5,
    fontWeight: "bold",
    backgroundColor: "#f0ffff",
    borderColor: "#00bfff",
    borderWidth: 1,
    borderRadius: 5,
    margin: 2,
    height: 100,
    marginVertical: 30,
    width: 300,
    alignSelf: "stretch",
    textAlign: "center",
  },
  adminOptions: {
    width: 350,
    height: 50,
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    textAlignVertical: "center",
    margin: 10,
  },
  adminColor: {
    backgroundColor: "#bad3",
    borderColor: "#9370db",
    borderWidth: 1,
    borderRadius: 5,
  },
  reviewButton: {
    marginLeft: 10,
    backgroundColor: "#00bfee",
    borderColor: "#9370db",
    borderWidth: 1,
    borderRadius: 5,
    textDecorationLine: "underline",
  },
  logout: {
    borderColor: "#00bfee",
    //backgroundColor: "#00bfff",
    textAlign: "center",
    borderBottomWidth: 1,
    fontWeight: "bold",
  },
  sorticon: { marginBottom: 15, height: 40 },
  submitButtonText: {
    //backgroundColor: "#ffffaa",
  },
});

/*
gray (`#808080`)
mediumorchid (`#ba55d3`)
mediumpurple (`#9370db`)
*/
